spring:
  config:
    import:
      - nacos:shared-seata.yaml # 从Nacos导入共享的seata配置

  datasource:
    url: jdbc:mysql://localhost:3306/permission?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 284100
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: permission-service

  cloud:
    nacos:
      server-addr: 192.168.91.135 # nacos地址
      config:
        file-extension: yaml # 文件后缀名

server:
  port: 8081


seata:
  enable-auto-data-source-proxy: true

feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持