spring:
  config:
    import:
      - nacos:shared-seata.yaml # 指定要从Nacos导入的dataId
      - nacos:shared-mq.yaml # 指定要从Nacos导入的dataId

  datasource:
    url: jdbc:mysql://localhost:3306/permission ?useSSL=false&serverTimezone=UTC
    username: root
    password: 284100
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: permission-service # 您的微服务名称

  main:
    allow-bean-definition-overriding: true # 允许Bean定义覆盖，某些情况下ShardingSphere会生成自己的DataSource Bean
  cloud:
    nacos:
      server-addr: 192.168.91.135 # nacos地址
      config:
        file-extension: yaml # 文件后缀名

server:
  port: 8081