spring:
  config:
    import:
      - nacos:shared-mq.yaml # 从Nacos导入共享的mq配置
  datasource:
    url: jdbc:mysql://localhost:3306/log?useSSL=false&serverTimezone=UTC8&allowPublicKeyRetrieval=true
    username: root
    password: 284100
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: logging-service
  main:
    allow-bean-definition-overriding: true # 允许Bean定义覆盖
  cloud:
    nacos:
      server-addr: 192.168.91.135 # nacos地址
      config:
        file-extension: yaml # 文件后缀名


server:
  port: 8083