# Spring 框架相关配置
spring:
  config:
    import:
    - nacos:shared-seata.yaml # 指定要从Nacos导入的dataId
    - nacos:shared-mq.yaml # 指定要从Nacos导入的dataId
  application:
    name: user-service # 微服务名称
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 192.168.91.135 # nacos地址
      config:
        file-extension: yaml # 文件后缀名
        import-check:
          enabled: false

  # ShardingSphere 配置 (Temporarily commented out for troubleshooting)
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/user_db_0?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
        username: root
        password: 284100
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/user_db_1?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
        username: root
        password: 284100
        driver-class-name: com.mysql.cj.jdbc.Driver

    sharding:
      tables:
        users:
          actualDataNodes: ds${0..1}.users_${0..1}
          tableStrategy:
            standard:
              shardingColumn: user_id
              shardingAlgorithmName: users_table_inline
          databaseStrategy:
            standard:
              shardingColumn: user_id
              shardingAlgorithmName: users_database_inline

      # 定义分片算法
      shardingAlgorithms:
        users_database_inline:
          type: INLINE
          props:
            algorithm-expression: ds$->{user_id % 2}
        users_table_inline:
          type: INLINE
          props:
            algorithm-expression: users_$->{user_id % 2}

    # ShardingSphere 属性配置
    props:
      show-sql: true

server:
  port: 8082

#logging:
#  level:
#    org.springframework: DEBUG
