# Spring 框架相关配置
spring:
  config:
    import:
    - nacos:shared-seata.yaml # 指定要从Nacos导入的dataId
    - nacos:shared-mq.yaml # 指定要从Nacos导入的dataId
  application:
    name: user-service # 微服务名称
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 192.168.91.135 # nacos地址
      config:
        file-extension: yaml # 文件后缀名
        import-check:
          enabled: false

# 由于 ShardingSphere 5.3.x 移除 Spring Boot Starter，这里改为使用 ShardingSphereDriver。
# 详细规则放在 `classpath:sharding.yaml`，见同级目录。
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml

server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
#logging:
#  level:
#    org.springframework: DEBUG
